tasks:
  - init: cd simulador-bovespa-functions && cd functions && npm install
  - init: cd simulador-bovespa-client && npm install && npm run start
  - before: npm i -g firebase-tools && export GOOGLE_APPLICATION_CREDENTIALS="/workspace/simulador-bovespa/simulador-bovespa-functions/firebaseToken.json" && firebase login --no-localhost
# In the simulador-bovespa-functions folder include a json file named "firebaseToken.json" that contains your firebase token
# And then run the: export GOOGLE_APPLICATION_CREDENTIALS="/workspace/simulador-bovespa/simulador-bovespa-functions/firebaseToken.json" && firebase serve --project <alias_or_project_id>
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - esbenp.prettier-vscode@4.7.0:kgoYSh1LwTixKtJtQWtodQ==
    - PKief.material-icon-theme@4.2.0:smoE258fj+WO32WcjZLU1A==