tasks:
  - init: cd simuladorBovespa-functions && cd functions && npm install 
  - before: npm i -g firebase-tools && export GOOGLE_APPLICATION_CREDENTIALS="/workspace/simulador-bovespa/simuladorBovespa-functions/Simulador Bovespa-aa447164afcc.json" && firebase login --no-localhost 
image:
  file: .gitpod.Dockerfile
