tasks:
  - init: cd simuladorBovespa-functions && cd functions && npm install && export GOOGLE_APPLICATION_CREDENTIALS="/workspace/simulador-bovespa/simuladorBovespa-functions/Simulador Bovespa-aa447164afcc.json"
  - before: npm i -g firebase-tools && firebase login --no-localhost
image:
  file: .gitpod.Dockerfile
